### ISSUE TITLE
Cache warming

### ISSUE THREAD

**Issue by ryanbrookepayne** [caddis/craft-presto#1]
Add functionality to re-cache pages that were cleared on a Craft event.

**Comment by maxstrebel** [comment]
I'll just +1 this. 

Though thanks for this plugin!

**Comment by ryanbrookepayne** [comment]
@maxstrebel Thanks for the feedback and support. I'm curious, do you use this plugin in any production sites you've built? We use it on all our client sites but we are not aware of anybody outside of our agency using it.

**Comment by maxstrebel** [comment]
@ryanbrookepayne I'm just about to use it in a weird constellation. I use craft as a kind of static site generator for a client which is not allowed to host neither a CMS nor to use element-api. Though I have to confess: if this works out well, I'll also use it to warm the cache in other projects - not with varnish but with presto cache plugin.

This is why I'll use it to not warm a cache but to get a complete static html output :)

**Comment by ryanbrookepayne** [comment]
@maxstrebel Good deal. Well let me know it works out and feel free to submit an issue if you run into any problems or have suggestions.

**Comment by maxstrebel** [comment]
@ryanbrookepayne sure thing, I will. One thing to note – I'll have to make the file ending dynamic (because in this case I'll need .php files as output). 

Would you welcome a dynamic implementation, where the default can changed from html to php as a pull-request?

Something like this, linked to a setting field?
`$extension = isset($pathInfo['extension']) ? pathInfo['extension'] : settings.cacheDefaultExtension;`

**Comment by ryanbrookepayne** [comment]
@maxstrebel yeah man. feel free to submit and we'll take a look. Not sure if we'll ever have an implementation like that, but it wouldn't hurt to have it in there.
